paths:
  /api/sessions/products:
    get:
      summary: Listar Products
      tags:
        - Products
      responses:
        200:
          descripton: Lista de Products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        500:
          description: Error interno del servidor
  /api/sessions/products/{uid}:
    get:
      summary: Obtiene un Products por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: uid
          required: true
          description: ID del Products
          schema:
            type: string
      responses:
        200:
          description: Products encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        404:
          description: Product no encontrado
        500:
          description: Error interno del servidor
    put:
      summary: Actualiza un Products por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: uid
          required: true
          description: ID del Products
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateProducts'
      responses:
        200:
          description: Products actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        404:
          description: Product no encontrado
        500:
          description: Error interno del servidor
    delete:
      summary: Elimina un Products por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: uid
          required: true
          description: ID del Products
          schema:
            type: string
      responses:
        200:
          description: Product eliminado
        404:
          description: Product no encontrado
        500:
          description: Error interno del servidor
components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: string
          description: ID del Products
        name:
          type: string
          description: Nombre del Restaurante
        image:
          type: string
          description: Imagen del Restaurante
        stock:
          type: string
          description: Stock del producto del Restaurante
        products: 
          id:
           type: number
           description: Identificador del menu
          name: 
           type: string
           description: Menu del resturante
          price:
           type: number
           description: Precio del menu 
      example:
        _id: 60f0a9c9e6b3c2b4b8a6b2a0
        name: Mazzaro
        image: https://proyectobackend-production-1746.up.railway.app/static/img/...
        stock: 10
        products:
         id: 1
         name: Muzzarela
         price: 4000
  requestBodies:
    updateProducts:
      type: object
      properties:
        name:
          type: string
          description: Nombre del Restaurante
        image:
          type: string
          description: Imagen del Restaourante del producto
        stock:
          type: string
          description: Stock disponible del producto
        products:
          type: array
          description: Informacion del menu
      example:
        name: "Mazzaro"
        image: "https://proyectobackend-production-1746.up.railway.app/static/img/..."
        stock: "10"
        products: 
          id: 1
          name: "Muzzarela"
          price: 4000